name: Ferric CI Linux

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:

env:
  RUST_INSTALL_LOCATION: /home/runner/Steam/steamapps/common/rust_dedicated

jobs:
  build:
    runs-on: ubuntu-latest
    # Prevent double running for push & pull_request events from the main repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'FerricTeam/Ferric'
    
    steps:
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Setup SteamCMD
      # You may pin to the exact commit or the version.
      # uses: CyberAndrii/setup-steamcmd@1a23c36fdf39218db07a406b1fda2775eb0636c3
      uses: CyberAndrii/setup-steamcmd@v1.1.4
      
    - uses: actions/checkout@v2.3.4
    
    #- name: Download xbuild
    #  shell: bash
    #  run: |
    #    sudo apt-get install nuget mono-devel mono-xbuild
    - name: Update nuget
      shell: bash
      run: |
        nuget update -self
    - name: Download APublicizer
      uses: carlosperate/download-file-action@v1.1.1
      with:
        file-url: 'https://github.com/iRebbok/APublicizer/releases/latest/download/native-linux-x64-release.tar.gz'
        file-name: 'release.tar.gz'
    - name: Download Rust Dedicated Server
      shell: bash
      run: |
        steamcmd +login anonymous +app_update 258550 validate +quit
    - name: Extract APublicizer
      shell: bash
      run: |
        tar -xzvf release.tar.gz
    - name: Publicize Assemblies
      shell: bash
      run: |
        ./APublicizer ${{ env.RUST_INSTALL_LOCATION }}/RustDedicated_Data/Managed/Assembly-CSharp.dll
        ./APublicizer ${{ env.RUST_INSTALL_LOCATION }}/RustDedicated_Data/Managed/Facepunch.Console.dll
    - name: Restore Packages
      run: nuget restore Ferric.sln
    - name: Build
      env:
        FERRIC_REFS: ${{ env.RUST_INSTALL_LOCATION }}/RustDedicated_Data/Managed
      shell: bash
      run: |
        xbuild Ferric.sln /p:Configuration="Release" /p:Platform="Any CPU"
    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Build Results
        path: |
            Ferric/bin/Release
            Ferric.Example/bin/Release
            Ferric.Injection/bin/Release
            Ferric.Patcher/bin/Release
